package com.weinhold.hexagon.aot;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The list of types the scanner needs to look at, written into the application at build time.
 * <p>This is what makes the endpoint work in a GraalVM native image. Runtime classpath
 * scanning reads {@code .class} resources through the classloader, and a native image has no
 * classpath to read — so a natively compiled service would serve an empty hexagon. Spring's
 * AOT engine runs on the JVM before compilation, where scanning still works, so
 * {@link HexagonScanAotProcessor} does the scan there and leaves the answer behind in
 * {@value #RESOURCE_LOCATION}.
 * <p>On the JVM the index is simply absent and the scanner scans as before. Where it is
 * present it is also authoritative and considerably faster than scanning — which is the point
 * open decision 2 of the contract was weighing.
 *
 * <h2>Format</h2>
 * One fully-qualified class name per line; blank lines and {@code #} comments are ignored.
 */
public final class HexagonComponentIndex {

    /** Classpath location of the index, relative to the classpath root. */
    public static final String RESOURCE_LOCATION = "META-INF/hexagon/components.idx";

    private static final Logger log = LoggerFactory.getLogger(HexagonComponentIndex.class);

    private final List<String> classNames;

    private HexagonComponentIndex(List<String> classNames) {
        this.classNames = classNames;
    }

    /**
     * Reads every index on the classpath and merges them, or returns {@code null} when none
     * is present — the ordinary case on the JVM, where the caller should scan instead.
     */
    public static HexagonComponentIndex load(ClassLoader classLoader) {
        var merged = new LinkedHashSet<String>();
        var found = false;
        try {
            var resources = Collections.list(classLoader.getResources(RESOURCE_LOCATION));
            for (var resource : resources) {
                found = true;
                try (var reader = new BufferedReader(
                        new InputStreamReader(resource.openStream(), StandardCharsets.UTF_8))) {
                    reader.lines().map(HexagonComponentIndex::stripComment).filter(line -> !line.isEmpty())
                          .forEach(merged::add);
                }
            }
        } catch (IOException ex) {
            log.warn("Could not read the hexagon component index, falling back to classpath scanning: {}", ex.toString());
            return null;
        }
        if (!found) {
            return null;
        }
        var classNames = new ArrayList<>(merged);
        Collections.sort(classNames);
        return new HexagonComponentIndex(List.copyOf(classNames));
    }

    /** Renders an index file. Names are sorted so the build output is reproducible. */
    public static String render(Collection<String> classNames) {
        var sorted = new ArrayList<>(new LinkedHashSet<>(classNames));
        Collections.sort(sorted);
        var content = new StringBuilder("# Generated by hexagon-collection-spring-boot-starter. Do not edit.\n");
        sorted.forEach(className -> content.append(className).append('\n'));
        return content.toString();
    }

    public List<String> getClassNames() {
        return this.classNames;
    }

    public boolean isEmpty() {
        return this.classNames.isEmpty();
    }

    private static String stripComment(String line) {
        var comment = line.indexOf('#');
        return (comment < 0 ? line : line.substring(0, comment)).trim();
    }

}
